

{{ config(materialized='view', alias='SLTRANS_SAMPLE') }}
---- Creates a version of the S_LEDGER for the past 2 years
--INSERT INTO #SLTRANS_SAMPLE
SELECT STPKEY,STDATE=CAST(CAST(STDATE AS DATE) AS DATETIME),STITYP,STCKEY,STVAL,STPOLN,STRSEQ,STASEQ
--into #SLTRANS_SAMPLE
---INTO #SLTRANS_SAMPLE
FROM Bennetts_Snapshot.dbo.sltrans WHERE
STDATE >= DATEADD(MM,-25,GETDATE())
--AND (CAST(STDATE AS DATE) <> CAST(GETDATE()-1 AS DATE) OR STPKEY NOT IN (SELECT STPKEY FROM Bennetts_Snapshot.dbo.SLTRANS  WITH(NOLOCK) WHERE CAST(STDATE AS DATE) >= CAST(GETDATE()-1 AS DATE)))
